# Generated by Django 5.1 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
